// Suspicious Process Access to LSASS Memory | 2a0b1b0e-af2b-4426-a58b-72866042c48c
Sysmon
| where EventID == 10
| where ((TargetImage endswith @"\lsass.exe" and (GrantedAccess =~ @"0x1010" or GrantedAccess =~ @"0x1410" or GrantedAccess =~ @"0x1438" or GrantedAccess =~ @"0x143a" or GrantedAccess =~ @"0x1fffff")) and (not(((SourceImage startswith @"C:\Windows\System32\" or SourceImage startswith @"C:\Windows\SysWOW64\") or (SourceImage startswith @"C:\ProgramData\Microsoft\Windows Defender\Platform\" and SourceImage endswith @"\MsMpEng.exe"))) or (SourceImage endswith @"\rundll32.exe" or SourceImage endswith @"\taskmgr.exe")))
