// Windows Event Log Clearing via Command Line | c62bd792-3b92-4bad-819c-fa3c123151d2
Sysmon
| where EventID == 1
| where ((Image endswith @"\wevtutil.exe" and (CommandLine contains @" cl " or CommandLine contains @" clear-log ")) or ((Image endswith @"\powershell.exe" or Image endswith @"\pwsh.exe") and (CommandLine contains @"Clear-EventLog" or CommandLine contains @"Remove-EventLog" or CommandLine contains @"Limit-EventLog" or CommandLine contains @".ClearLog(" or CommandLine contains @"Clear-WinEvent")) or (Image endswith @"\wmic.exe" and (CommandLine contains @"nteventlog" and CommandLine contains @"cleareventlog")))
