#!/usr/bin/env python3
"""
coverage.py - generate ATT&CK coverage artifacts straight from the rules.

Outputs
  coverage/attack_navigator_layer.json  -> import into MITRE ATT&CK Navigator
  docs/COVERAGE.md                      -> human-readable coverage matrix

A technique's score reflects *validated* coverage: rules with passing
true-positive tests score higher than untested ones, so the heatmap never
overstates what the SOC can actually detect.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_tests import run  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
LEVEL_SCORE = {"informational": 20, "low": 40, "medium": 60, "high": 80, "critical": 100}
TACTIC_ORDER = ["initial-access", "execution", "persistence", "privilege-escalation",
                "defense-evasion", "credential-access", "discovery", "lateral-movement",
                "collection", "command-and-control", "exfiltration", "impact"]


def collect() -> list[dict]:
    results = run(None)
    status = defaultdict(lambda: {"tp": 0, "tp_pass": 0, "all_pass": True})
    for r in results:
        s = status[r["detection"]]
        s["all_pass"] &= r["passed"]
        if r["kind"] == "true_positive":
            s["tp"] += 1
            s["tp_pass"] += r["passed"]

    rules = []
    for folder in sorted(p for p in (ROOT / "detections").iterdir() if p.is_dir()):
        rule = yaml.safe_load((folder / "rule.yml").read_text(encoding="utf-8"))
        tags = rule.get("tags", [])
        rules.append({
            "folder": folder.name,
            "title": rule["title"],
            "level": rule["level"],
            "techniques": [t.split(".", 1)[1].upper() for t in tags if re.match(r"^attack\.t\d{4}", t)],
            "tactics": [t.split(".", 1)[1] for t in tags
                        if t.startswith("attack.") and not re.match(r"^attack\.t\d{4}", t)],
            **status[folder.name],
        })
    return rules


def navigator_layer(rules: list[dict]) -> dict:
    per_tech: dict[str, list[dict]] = defaultdict(list)
    for r in rules:
        for t in r["techniques"]:
            per_tech[t].append(r)
    techniques = []
    for tid, rs in sorted(per_tech.items()):
        best = max(LEVEL_SCORE[r["level"]] for r in rs)
        validated = all(r["all_pass"] and r["tp_pass"] > 0 for r in rs)
        techniques.append({
            "techniqueID": tid,
            "score": best if validated else best // 2,
            "comment": "\n".join(f"{r['title']} ({r['folder']}) - "
                                 f"{'validated' if r['all_pass'] else 'FAILING TESTS'}" for r in rs),
            "enabled": True,
            "showSubtechniques": True,
            "metadata": [{"name": "rules", "value": str(len(rs))}],
        })
    return {
        "name": "Purple Lab - Validated Detection Coverage",
        "versions": {"attack": "16", "navigator": "5.1.0", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated by tools/coverage.py from tested Sigma rules.",
        "techniques": techniques,
        "gradient": {"colors": ["#ffe5e5", "#ff9f43", "#10ac84"], "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "Validated high-fidelity detection", "color": "#10ac84"},
            {"label": "Detection present, lower confidence/untested", "color": "#ff9f43"},
        ],
        "layout": {"layout": "side", "showName": True, "showID": True},
        "hideDisabled": False,
    }


def markdown(rules: list[dict]) -> str:
    def tactic_rank(r: dict) -> int:
        ranks = [TACTIC_ORDER.index(t) for t in r["tactics"] if t in TACTIC_ORDER]
        return min(ranks) if ranks else 99

    lines = [
        "# Detection Coverage",
        "",
        "> Auto-generated by `tools/coverage.py` - do not edit by hand.",
        "",
        f"**{len(rules)} detections** covering **{len({t for r in rules for t in r['techniques']})} ATT&CK techniques**, "
        f"**{sum(r['tp'] for r in rules)} true-positive** test cases.",
        "",
        "| Tactic | Technique(s) | Detection | Level | TP tests | Status |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(rules, key=lambda r: (tactic_rank(r), r["folder"])):
        tactic = ", ".join(t for t in r["tactics"] if t in TACTIC_ORDER) or "-"
        techs = ", ".join(f"[{t}](https://attack.mitre.org/techniques/{t.replace('.', '/')}/)" for t in r["techniques"])
        status = "✅ validated" if r["all_pass"] else "❌ failing"
        lines.append(f"| {tactic} | {techs} | [{r['title']}](../detections/{r['folder']}/) | "
                     f"{r['level']} | {r['tp_pass']}/{r['tp']} | {status} |")
    lines += ["", "Import `coverage/attack_navigator_layer.json` into "
              "[ATT&CK Navigator](https://mitre-attack.github.io/attack-navigator/) for the heatmap.", ""]
    return "\n".join(lines)


def main() -> int:
    rules = collect()
    (ROOT / "coverage").mkdir(exist_ok=True)
    (ROOT / "coverage" / "attack_navigator_layer.json").write_text(
        json.dumps(navigator_layer(rules), indent=2) + "\n", encoding="utf-8")
    (ROOT / "docs" / "COVERAGE.md").write_text(markdown(rules), encoding="utf-8")
    print(f"[+] coverage generated for {len(rules)} detections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
